import React from 'react';
import client from '../apolloClient';
import {ApolloProvider} from '@apollo/client';
import Head from "next/head";
import DisplayMemo from '../components/DisplayMemo';
import Header from "@/components/Nav";

// made by Yu Han
// It utilizes ApolloProvider to provide access to the Apollo client
// for fetching data through GraphQL. The memo data is fetched and
// displayed using the DisplayMemo component.
export default function Display() {
    return (
        <>
            <Head>
                <title>Display Memo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main style={{ display: "flex", flexDirection: "column", justifyContent: "space-between",
                alignItems: "center",
                padding: "6rem",
                minHeight: "100vh"}}>
                <ApolloProvider client={client}>
                    <DisplayMemo/>
                </ApolloProvider>
            </main>
        </>
    );
}
