import React from 'react';
import client from '../apolloClient';
import {ApolloProvider} from '@apollo/client';
import Head from "next/head";
import DisplayMemo from '../components/DisplayMemo';
import Header from "@/components/Nav";
import styles from "../styles/Home.module.css";

export default function Display() {
    return (
        <>
            <Head>
                <title>Display Memo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main className={`${styles.main} `}>
                <ApolloProvider client={client}>
                    <DisplayMemo/>
                </ApolloProvider>
            </main>
        </>
    );
}
