import Head from "next/head";
import React from "react";
import Header from "../components/Nav";


export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header/>
        <main style={{
            display: "flex", flexDirection: "column", justifyContent: "space-between",
            alignItems: "center",
            padding: "6rem",
            minHeight: "100vh"
        }}>

        </main>
    </>
  );
}
