import React from 'react';
import client from '../apolloClient';
import {ApolloProvider} from '@apollo/client';
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import InputMemo from '../components/InputMemo';
import Header from "@/components/Nav";

export default function Update() {
    return (
        <>
            <Head>
                <title>Update Memo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main className={`${styles.main} `}>
                <h2>Update Memo Wall</h2>
                <ApolloProvider client={client}>
                    <InputMemo/>
                </ApolloProvider>
            </main>
        </>
    );
}
