import React from 'react';
import client from '../apolloClient';
import {ApolloProvider} from '@apollo/client';
import Head from "next/head";
import InputMemo from '../components/InputMemo';
import Header from "@/components/Nav";

// made by Yu Han
// This page renders the main update page for memos. It utilizes ApolloProvider
// to provide access to the Apollo client for updating data through GraphQL. The InputMemo
// component is used to input and submit memo updates.

export default function Update() {
    return (
        <>
            <Head>
                <title>Update Memo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main style={{
                display: "flex", flexDirection: "column", justifyContent: "space-between",
                alignItems: "center",
                padding: "6rem",
                minHeight: "100vh"
            }}>
                <ApolloProvider client={client}>
                    <InputMemo/>
                </ApolloProvider>
            </main>
        </>
    );
}
